# Generated by Django 4.2 on 2025-07-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_time'], 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time'], 'verbose_name_plural': 'Flights'},
        ),
    ]
